services:
  nextapp:
    container_name: nextapp
    image: nextapp
    environment:
      - WATCHPACK_POLLING=true
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules 
    ports:
      - '3000:3000'
